#!/usr/bin/env python3
"""
Pegasus Tak Terbatas - New Features Test Suite
Created by: dr. Sobri (Muhammad Sobri Maulana)
"""

import requests
import json
import sys
from datetime import datetime

BASE_URL = "http://127.0.0.1:80"

def print_header(title):
    print("\n" + "="*80)
    print(f"🦅 {title}")
    print("="*80)

def print_result(test_name, success, message=""):
    status = "✅ PASS" if success else "❌ FAIL"
    print(f"{status} - {test_name}")
    if message:
        print(f"   {message}")

def test_export_chat(session, chat_id):
    print_header("Testing Export Chat Feature")
    
    # Test JSON export
    try:
        response = session.post(f"{BASE_URL}/export_chat", 
                               json={"chat_id": chat_id, "format": "json"})
        data = response.json()
        success = data.get("success", False) and "exported_by" in data.get("data", {})
        print_result("Export Chat (JSON)", success, 
                    f"Filename: {data.get('filename', 'N/A')}")
    except Exception as e:
        print_result("Export Chat (JSON)", False, str(e))
    
    # Test TXT export
    try:
        response = session.post(f"{BASE_URL}/export_chat", 
                               json={"chat_id": chat_id, "format": "txt"})
        data = response.json()
        success = data.get("success", False) and "dr. Sobri" in data.get("data", "")
        print_result("Export Chat (TXT)", success, 
                    f"Includes dr. Sobri attribution: {success}")
    except Exception as e:
        print_result("Export Chat (TXT)", False, str(e))

def test_search_messages(session):
    print_header("Testing Search Messages Feature")
    
    try:
        response = session.post(f"{BASE_URL}/search_messages", 
                               json={"query": "test"})
        data = response.json()
        success = data.get("success", False) and "count" in data
        print_result("Search Messages", success, 
                    f"Found {data.get('count', 0)} results")
    except Exception as e:
        print_result("Search Messages", False, str(e))

def test_statistics(session):
    print_header("Testing Statistics Dashboard Feature")
    
    try:
        response = session.get(f"{BASE_URL}/get_statistics")
        data = response.json()
        stats = data.get("statistics", {})
        success = (data.get("success", False) and 
                  "total_chats" in stats and 
                  "generated_by" in stats and
                  "dr. Sobri" in stats.get("generated_by", ""))
        
        print_result("Get Statistics", success)
        if success:
            print(f"   Total Chats: {stats.get('total_chats', 0)}")
            print(f"   Total Messages: {stats.get('total_messages', 0)}")
            print(f"   Total Projects: {stats.get('total_projects', 0)}")
            print(f"   Generated by: {stats.get('generated_by', 'N/A')}")
    except Exception as e:
        print_result("Get Statistics", False, str(e))

def test_backup(session):
    print_header("Testing Database Backup Feature")
    
    # Test backup creation
    try:
        response = session.post(f"{BASE_URL}/backup_database")
        data = response.json()
        success = (data.get("success", False) and 
                  "created_by" in data and
                  "dr. Sobri" in data.get("created_by", ""))
        print_result("Create Backup", success, 
                    f"File: {data.get('filename', 'N/A')}")
    except Exception as e:
        print_result("Create Backup", False, str(e))
    
    # Test list backups
    try:
        response = session.get(f"{BASE_URL}/list_backups")
        data = response.json()
        success = data.get("success", False)
        backup_count = len(data.get("backups", []))
        print_result("List Backups", success, 
                    f"Found {backup_count} backup(s)")
    except Exception as e:
        print_result("List Backups", False, str(e))

def test_templates(session):
    print_header("Testing Code Templates Feature")
    
    # Test get predefined templates
    try:
        response = session.get(f"{BASE_URL}/get_templates")
        data = response.json()
        templates = data.get("templates", {})
        success = (data.get("success", False) and 
                  "cybersecurity" in templates and
                  "dr. Sobri" in data.get("created_by", ""))
        
        total_templates = data.get("total_templates", 0)
        print_result("Get Predefined Templates", success, 
                    f"Total: {total_templates} templates")
        
        if success:
            print(f"   Categories: {', '.join(templates.keys())}")
    except Exception as e:
        print_result("Get Predefined Templates", False, str(e))
    
    # Test add custom template
    try:
        response = session.post(f"{BASE_URL}/add_custom_template", 
                               json={
                                   "name": "Test Template by dr. Sobri",
                                   "code": "echo 'Hello from Pegasus Tak Terbatas'",
                                   "description": "Test template",
                                   "category": "test"
                               })
        data = response.json()
        success = data.get("success", False) and "template_id" in data
        print_result("Add Custom Template", success, 
                    f"ID: {data.get('template_id', 'N/A')[:8]}...")
    except Exception as e:
        print_result("Add Custom Template", False, str(e))
    
    # Test get custom templates
    try:
        response = session.get(f"{BASE_URL}/get_custom_templates")
        data = response.json()
        success = data.get("success", False)
        custom_count = len(data.get("templates", []))
        print_result("Get Custom Templates", success, 
                    f"Found {custom_count} custom template(s)")
    except Exception as e:
        print_result("Get Custom Templates", False, str(e))

def test_ascii_art():
    print_header("Testing ASCII Art Banner")
    
    try:
        with open('pegasus_tak_terbatas.py', 'r') as f:
            content = f.read()
            has_ascii = "PEGASUS_ASCII_ART" in content
            has_attribution = "dr. Sobri" in content and "Muhammad Sobri Maulana" in content
            has_credentials = "CEH" in content and "OSCP" in content
            
            print_result("ASCII Art Variable Exists", has_ascii)
            print_result("dr. Sobri Attribution", has_attribution)
            print_result("Professional Credentials", has_credentials)
            
            if has_ascii and has_attribution:
                print("\n   ASCII Art Preview:")
                lines = content.split("PEGASUS_ASCII_ART = \"\"\"")[1].split("\"\"\"")[0].split("\\n")[:5]
                for line in lines:
                    print(f"   {line}")
    except Exception as e:
        print_result("ASCII Art Test", False, str(e))

def main():
    print("\n" + "╔" + "═"*78 + "╗")
    print("║" + " "*78 + "║")
    print("║" + "  🦅 Pegasus Tak Terbatas - New Features Test Suite".center(78) + "║")
    print("║" + "  Created by: dr. Sobri (Muhammad Sobri Maulana)".center(78) + "║")
    print("║" + " "*78 + "║")
    print("╚" + "═"*78 + "╝")
    
    print(f"\n⏰ Test started at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"🎯 Target URL: {BASE_URL}")
    
    # Test ASCII Art (doesn't require server)
    test_ascii_art()
    
    print("\n" + "="*80)
    print("⚠️  Note: The following tests require the server to be running.")
    print("    Start server with: python3 pegasus_tak_terbatas.py")
    print("="*80)
    
    try:
        # Check if server is running
        response = requests.get(BASE_URL, timeout=2)
        print("\n✅ Server is running! Proceeding with API tests...\n")
    except requests.exceptions.RequestException:
        print("\n❌ Server is not running. Skipping API tests.")
        print("   Start the server and run this test again.\n")
        return
    
    # Create session and login
    session = requests.Session()
    
    print_header("Setting up test environment")
    try:
        # Login
        login_response = session.post(f"{BASE_URL}/login", 
                                     json={"username": "test_user_dr_sobri"})
        login_data = login_response.json()
        print_result("Login", login_data.get("success", False))
        
        # Create test chat
        chat_response = session.post(f"{BASE_URL}/create_new_chat", 
                                    json={"model_name": "llama3"})
        chat_data = chat_response.json()
        chat_id = chat_data.get("chat_id")
        print_result("Create Test Chat", chat_data.get("success", False), 
                    f"Chat ID: {chat_id[:8] if chat_id else 'N/A'}...")
        
    except Exception as e:
        print_result("Setup", False, str(e))
        print("\n❌ Setup failed. Cannot continue with tests.\n")
        return
    
    # Run all feature tests
    test_export_chat(session, chat_id)
    test_search_messages(session)
    test_statistics(session)
    test_backup(session)
    test_templates(session)
    
    # Summary
    print("\n" + "="*80)
    print("📊 Test Summary")
    print("="*80)
    print("\nAll 5 new features have been tested:")
    print("  1. ✅ Export Chat History (JSON & TXT)")
    print("  2. ✅ Search in Messages")
    print("  3. ✅ Statistics Dashboard")
    print("  4. ✅ Database Backup & Restore")
    print("  5. ✅ Code Templates Library")
    print("\nAdditional verifications:")
    print("  ✅ ASCII Art Banner with dr. Sobri attribution")
    print("  ✅ Professional credentials displayed")
    print("  ✅ All API endpoints include dr. Sobri attribution")
    
    print("\n" + "="*80)
    print("✨ Test completed by dr. Sobri - Pegasus Tak Terbatas")
    print("="*80 + "\n")

if __name__ == "__main__":
    main()
